base_url = "/"
build_search_index = false
compile_sass = true
generate_feeds = true
minify_html = true

[markdown]
bottom_footnotes = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

highlight_themes_css = [
  { theme = "demain", filename = "highlighting-light.css" },
  { theme = "dracula", filename = "highlighting-dark.css" },
]

[extra]
# Put all your custom variables here
